### ISSUE TITLE
PeerManager().SelectPeers returns peer which don't support the protocol

### ISSUE THREAD

**Issue by kaichaosun** [logos-messaging/logos-delivery-go#1111] opened 2024-05-24 05:10 UTC
I'm trying to use PeerManager SelectPeers for `store.StoreQueryID_v300`, it returned a peer id and using it for the hash query, got  error:
```
store.queryByHash failed                 requestID=0x28af3edd739b2acbfbfd7c915445cfd0c3ba0a04956258dae5b6203738b7f6b9 error="failed to negotiate protocol: protocols not supported: [/vac/waku/store-query/3.0.0]"
```

**Comment by chaitanyaprem** [comment] 2024-05-24 06:43
That is odd. 
Can you provide debug logs for this scenario? 
I want to see if the node has advertise Storev3 as part of its identity protocol. Because that is where protocols for peer are stored within peerStore. 
Another method is if someone explicitly adds a peer indicating it supports a specific protocol, then also this information is added to peerStore.

**Comment by chaitanyaprem** [comment] 2024-05-24 11:24
Can you let me know the query to which Store peer has failed?
Because all nodes in the fleets don't have store enabled, and I am not sure if all of them have storev3 enabled as well.

**Comment by chaitanyaprem** [comment] 2024-05-24 11:26
One scenario i could think of is this:
ENR of the fleet node or Store node indicates it has store protocol, based on which the local go-waku node is including the peer to support Storev3. But what if fleet node is still using storev2? In that case go-waku thinks node supports Storev3, but actually fleet supports Storev2. 
It would help to get details of the peer hence.

**Comment by chaitanyaprem** [comment] 2024-05-24 11:34
> One scenario i could think of is this: ENR of the fleet node or Store node indicates it has store protocol, based on which the local go-waku node is including the peer to support Storev3. But what if fleet node is still using storev2? In that case go-waku thinks node supports Storev3, but actually fleet supports Storev2. It would help to get details of the peer hence.

I can confirm from your logs that you are using `shards.test` fleet which is not yet upgraded to latest nwaku release. Hence this is what must be happening, Can you change fleet to `shards.staging` and confirm if you are still facing this issue?

**Comment by chaitanyaprem** [comment] 2024-06-07 10:06
@kaichaosun are you still seeing this issue?

if not, we can close this.

**Closed as completed** 2024-06-07 13:19 UTC
